# This folder contains no application-specific settings and can be reused as is.
replicaCount: 1
revisionHistoryLimit: 2
nameOverride: platform-teams-notification-api
appPath: /platform-teams-notification-api
healthUrl: /health
environment: TBD
env:
  ASPNETCORE_ENVIRONMENT: "dev"
