apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platform-teams-notification-api-exception-detected-prod
  labels:
    dash0.com/id: platform-teams-notification-api-exception-detected-prod
spec:
  groups:
    - name: Alerting
      interval: 5m
      rules:
        - alert: Teams Notifications Api Exception Detected (prod)
          expr: sum(increase({otel_metric_name="dash0.spans", service_name="platform-teams-notification-api", otel_span_status_code="ERROR"}[5m])) > 0
          for: 0m
          annotations:
            summary: "Unhandled exception detected in platform-teams-notification-api (prod)"
            description: "One or more spans with ERROR status were recorded for platform-teams-notification-api in prod over the last 5 minutes."
          labels:
            environment: prod
            service: platform-teams-notification-api
