apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platform-teams-notification-api-exception-detected-__ENVIRONMENT__
  labels:
    dash0.com/id: platform-teams-notification-api-exception-detected-__ENVIRONMENT__
spec:
  groups:
    - name: Alerting
      interval: 5m
      rules:
        - alert: Teams Notifications Api Exception Detected - Spans (__ENVIRONMENT__)
          expr: sum by (service_name, k8s_pod_name) (increase({otel_metric_name="dash0.spans", service_name="platform-teams-notification-api", otel_span_status_code="ERROR"}[5m])) > 0
          for: 0m
          annotations:
            summary: "Unhandled exception detected in platform-teams-notification-api (__ENVIRONMENT__)"
            description: "One or more spans with ERROR status were recorded for platform-teams-notification-api in __ENVIRONMENT__ over the last 5 minutes."
            dash0.com/notification-channel-ids: platform-teams-notification-api-apps-team-__ENVIRONMENT__
          labels:
            environment: __ENVIRONMENT__
            service: platform-teams-notification-api
        - alert: Teams Notifications Api Exception Detected - Logs (__ENVIRONMENT__)
          expr: sum by (service_name, k8s_pod_name) (increase({otel_metric_name="dash0.logs", service_name="platform-teams-notification-api", otel_log_severity_range="FATAL"}[5m])) > 0
          for: 0m
          annotations:
            summary: "Unhandled exception detected in platform-teams-notification-api (__ENVIRONMENT__)"
            description: "One or more FATAL logs were recorded for platform-teams-notification-api in __ENVIRONMENT__ over the last 5 minutes."
          labels:
            environment: __ENVIRONMENT__
            service: platform-teams-notification-api
