{{- $name := include "platform-teams-notification-api.name" . -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
    version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $name }}
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "compute-aks-platform-teams-notification-api-{{ .Values.environment }}-k8s-sa"
      containers:
        - name: {{ $name }}
          image: computeaksacr.azurecr.io/{{ $name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.startupProbe.path }}
              scheme: HTTP
              port: 8080
          livenessProbe:
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              scheme: HTTP
              port: 8080
          readinessProbe:
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              scheme: HTTP
              port: 8080
          env:
          - name: ASPNETCORE_URLS
            value: "http://+:8080"
        {{- range $key, $value := .Values.env }}
          - name: {{ $key | upper | replace "." "_" }}
            value: {{ $value | quote }}
        {{- end }} 
      nodeSelector:
        agentpool: platform