{{- $name := include "platform-teams-notification-api.name" . -}}
apiVersion: ingress.uniphar.ie/v1
kind: AbstractIngress
metadata:
  name: {{ $name }}
spec:
  isPrivate: true
  serviceName: {{ $name }}-srv
  servicePort: 80
  urlPrefix: {{ .Values.appPath }}